/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Read Root */
		get: operations["read_root__get"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/score": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** Score Candidates */
		post: operations["score_candidates_score_post"]
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		/** Candidate */
		Candidate: {
			/** Id */
			id: string
			/** Name */
			name: string
			/** Resume */
			resume: string
		}
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][]
		}
		/** ScoreRequest */
		ScoreRequest: {
			/** Job Description */
			job_description: string
			/** Candidates */
			candidates: components["schemas"]["Candidate"][]
		}
		/** ScoredCandidate */
		ScoredCandidate: {
			/** Id */
			id: string
			/** Name */
			name: string
			/** Score */
			score: number
			/** Highlights */
			highlights: string[]
		}
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[]
			/** Message */
			msg: string
			/** Error Type */
			type: string
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	read_root__get: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": unknown
				}
			}
		}
	}
	score_candidates_score_post: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				"application/json": components["schemas"]["ScoreRequest"]
			}
		}
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["ScoredCandidate"][]
				}
			}
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["HTTPValidationError"]
				}
			}
		}
	}
}
